"""Execution layer modules."""
from .execution_gate_v1 import evaluate_execution_gate, reservation_required_quantity
from .order_router_v1 import (
    RoutedCanonicalOrder,
    canonical_order_router_hash,
    canonical_order_router_payload,
    route_trade_ticket,
    route_trade_ticket_from_handoff,
)
from .paper_adapter_v1 import (
    build_order_state_transition,
    build_paper_order,
    gate_rejection_journal_payload,
    paper_order_journal_payload,
    paper_order_journal_payload_with_status,
)
from .paper_fill_simulator_v1 import (
    PaperFillSimulationResult,
    build_fill_transition,
    fill_journal_payload,
    order_fill_status_journal_payload,
    simulate_quote_based_fill,
)
from .signal_to_order_v1 import (
    ExecutionContextRecord,
    PersistedExecutionContextRecord,
    build_execution_context,
    build_execution_context_record,
    build_order_from_intent,
    build_signal_order_intent,
    build_signal_order_intent_from_handoff,
    canonical_order_handoff_hash,
    canonical_order_handoff_payload,
    enqueue_execution_context_upserts,
    execution_context_record_to_row,
    hydrate_execution_context,
    load_execution_context_record,
    load_account_trading_capability,
    load_market_capability,
)
from .trade_ticket_v1 import bind_trade_ticket_handoff, build_trade_ticket, load_trade_ticket
from .watch_only_gate_v3 import decide_watch_only

__all__ = [
    "ExecutionContextRecord",
    "PersistedExecutionContextRecord",
    "PaperFillSimulationResult",
    "RoutedCanonicalOrder",
    "bind_trade_ticket_handoff",
    "build_execution_context",
    "build_execution_context_record",
    "build_fill_transition",
    "build_order_state_transition",
    "build_order_from_intent",
    "build_paper_order",
    "build_signal_order_intent",
    "build_signal_order_intent_from_handoff",
    "build_trade_ticket",
    "canonical_order_router_hash",
    "canonical_order_router_payload",
    "canonical_order_handoff_hash",
    "canonical_order_handoff_payload",
    "decide_watch_only",
    "enqueue_execution_context_upserts",
    "evaluate_execution_gate",
    "execution_context_record_to_row",
    "fill_journal_payload",
    "gate_rejection_journal_payload",
    "hydrate_execution_context",
    "load_execution_context_record",
    "load_account_trading_capability",
    "load_market_capability",
    "load_trade_ticket",
    "paper_order_journal_payload",
    "paper_order_journal_payload_with_status",
    "order_fill_status_journal_payload",
    "route_trade_ticket",
    "route_trade_ticket_from_handoff",
    "reservation_required_quantity",
    "simulate_quote_based_fill",
]
