CREATE TABLE IF NOT EXISTS runtime.external_fill_observations (
    observation_id TEXT PRIMARY KEY,
    attempt_id TEXT NOT NULL,
    request_id TEXT NOT NULL,
    ticket_id TEXT NOT NULL,
    order_id TEXT,
    wallet_id TEXT NOT NULL,
    execution_context_id TEXT NOT NULL,
    exchange TEXT NOT NULL,
    observation_kind TEXT NOT NULL,
    external_order_id TEXT,
    external_trade_id TEXT NOT NULL,
    market_id TEXT NOT NULL,
    token_id TEXT NOT NULL,
    outcome TEXT NOT NULL,
    side TEXT NOT NULL,
    price DECIMAL(18,8) NOT NULL,
    size DECIMAL(18,8) NOT NULL,
    fee DECIMAL(18,8) NOT NULL,
    fee_rate_bps INTEGER NOT NULL,
    external_status TEXT NOT NULL,
    observed_at TIMESTAMP NOT NULL,
    error TEXT,
    raw_observation_json TEXT NOT NULL
);
