"""Weather forecast package."""

from .adapters import NWSAdapter, OpenMeteoAdapter, StdDevResolutionSummary, resolve_std_dev_summary
from .calibration import (
    CalibrationConfidenceSummary,
    CalibrationProfileV2,
    DuckDBForecastStdDevProvider,
    ForecastCalibrationV2Summary,
    build_calibration_lookup_key,
    calibration_confidence_from_metrics,
    calibration_regime_bucket,
    calibration_v2_context_for_probability,
    build_forecast_calibration_sample,
    forecast_distribution_mean,
    forecast_distribution_std_dev,
    forecast_horizon_bucket,
    materialize_forecast_calibration_profiles_v2,
    season_bucket,
    threshold_probability_bucket,
    threshold_probability_profile_for_probability,
)
from .cache import InMemoryForecastCache
from .persistence import (
    WEATHER_FORECAST_CALIBRATION_SAMPLE_COLUMNS,
    WEATHER_FORECAST_CALIBRATION_PROFILE_V2_COLUMNS,
    WEATHER_FORECAST_RUN_COLUMNS,
    WEATHER_FORECAST_REPLAY_COLUMNS,
    WEATHER_FORECAST_REPLAY_DIFF_COLUMNS,
    WEATHER_SOURCE_HEALTH_SNAPSHOT_COLUMNS,
    enqueue_forecast_calibration_sample_upserts,
    enqueue_forecast_calibration_profile_v2_upserts,
    enqueue_forecast_replay_diff_upserts,
    enqueue_forecast_replay_upserts,
    enqueue_source_health_snapshot_upserts,
    build_forecast_run_record,
    forecast_calibration_profile_v2_to_row,
    forecast_calibration_sample_to_row,
    enqueue_forecast_run_upserts,
    forecast_run_to_row,
    source_health_snapshot_to_row,
)
from .service import AdapterRouter, ForecastDistribution, ForecastService, build_forecast_request, normalize_forecast_source_name
from .replay import (
    build_forecast_replay_diff_records,
    build_forecast_replay_record,
    build_forecast_replay_request,
    load_original_pricing_outputs,
    load_replay_inputs,
    recompute_forecast_run,
    recompute_pricing_outputs,
    run_forecast_replay,
)

__all__ = [
    "AdapterRouter",
    "CalibrationConfidenceSummary",
    "CalibrationProfileV2",
    "DuckDBForecastStdDevProvider",
    "ForecastCalibrationV2Summary",
    "ForecastDistribution",
    "ForecastService",
    "InMemoryForecastCache",
    "NWSAdapter",
    "OpenMeteoAdapter",
    "StdDevResolutionSummary",
    "WEATHER_FORECAST_CALIBRATION_SAMPLE_COLUMNS",
    "WEATHER_FORECAST_CALIBRATION_PROFILE_V2_COLUMNS",
    "WEATHER_FORECAST_REPLAY_COLUMNS",
    "WEATHER_FORECAST_REPLAY_DIFF_COLUMNS",
    "WEATHER_FORECAST_RUN_COLUMNS",
    "WEATHER_SOURCE_HEALTH_SNAPSHOT_COLUMNS",
    "build_calibration_lookup_key",
    "calibration_confidence_from_metrics",
    "calibration_regime_bucket",
    "calibration_v2_context_for_probability",
    "build_forecast_calibration_sample",
    "build_forecast_replay_diff_records",
    "build_forecast_replay_record",
    "build_forecast_replay_request",
    "build_forecast_run_record",
    "build_forecast_request",
    "enqueue_forecast_calibration_sample_upserts",
    "enqueue_forecast_calibration_profile_v2_upserts",
    "enqueue_forecast_replay_diff_upserts",
    "enqueue_forecast_replay_upserts",
    "enqueue_forecast_run_upserts",
    "enqueue_source_health_snapshot_upserts",
    "forecast_calibration_sample_to_row",
    "forecast_calibration_profile_v2_to_row",
    "forecast_distribution_mean",
    "forecast_distribution_std_dev",
    "forecast_horizon_bucket",
    "forecast_run_to_row",
    "load_original_pricing_outputs",
    "load_replay_inputs",
    "normalize_forecast_source_name",
    "recompute_forecast_run",
    "recompute_pricing_outputs",
    "run_forecast_replay",
    "resolve_std_dev_summary",
    "season_bucket",
    "materialize_forecast_calibration_profiles_v2",
    "threshold_probability_bucket",
    "threshold_probability_profile_for_probability",
    "source_health_snapshot_to_row",
]
